--[[ Changes in this file:
    * Modified function F_LoadAllActionTrees, may require testing
]]

CharacterActionTreesBranches = {
    "/Global/Actions",
    "/Global/HitTree",
    "/Global/Weapons",
    "/Global/Vehicles",
    "/Global/WProps",
    "/Global/Ambient",
    "/Global/Cameras",
    "/Global/PlayerFacial",
    "/Global/NPCFacial",
    "/Global/CutScenes",
    "/Global/SimpleLoco",
    "/Global/Bat",
    "/Global/BasketBall",
    "/Global/BBGun",
    "/Global/Books",
    "/Global/FlashLight",
    "/Global/JBroom",
    "/Global/Gun",
    "/Global/KickMeSign",
    "/Global/NonWeapon",
    "/Global/Shields",
    "/Global/Slasher",
    "/Global/SledgeHammer",
    "/Global/SlingShot",
    "/Global/Spraycan",
    "/Global/SnowShovel",
    "/Global/Thrown",
    "/Global/Umbrella",
    "/Global/WCamera",
    "/Global/WFireExt",
    "/Global/WaterPipe",
    "/Global/EdgarShield"
}
CharacterActionTrees = {
    "Act/Globals/GlobalActions.act",
    "Act/Globals/SimpleLoco.act",
    "Act/HitTree.act",
    "Act/Weapons.act",
    "Act/Vehicles.act",
    "Act/WProps.act",
    "Act/Anim/Ambient.act",
    "Act/Globals/Cameras.act",
    "Act/Globals/PlayerFacial.act",
    "Act/Globals/NPCFacial.act",
    "Act/Globals/CutScene.act",
    "Act/Weapons/Basketball.act",
    "Act/Weapons/Bat.act",
    "Act/Weapons/BBGun.act",
    "Act/Weapons/Books.act",
    "Act/Weapons/FlashLight.act",
    "Act/Weapons/Gun.act",
    "Act/Weapons/KickMeSign.act",
    "Act/Weapons/JBroom.act",
    "Act/Weapons/NonWeapon.act",
    "Act/Weapons/Shields.act",
    "Act/Weapons/Slasher.act",
    "Act/Weapons/SledgeHammer.act",
    "Act/Weapons/SlingShot.act",
    "Act/Weapons/Spraycan.act",
    "Act/Weapons/SnowShovel.act",
    "Act/Weapons/Thrown.act",
    "Act/Weapons/Umbrella.act",
    "Act/Weapons/WCamera.act",
    "Act/Weapons/WFireExt.act",
    "Act/Weapons/WaterPipe.act",
    "Act/Weapons/EdgarShield.act"
}
PropActionTrees = {
    "Act/Props/Garbagecan.act",
    "Act/Props/Rails.act",
    "Act/Props/Tags.act",
    "Act/Props/Bed.act",
    "Act/Props/Door.act",
    "Act/Props/AniDice.act",
    "Act/Props/AniGlobe.act",
    "Act/Props/BCatcher.act",
    "Act/Props/Bed.act",
    "Act/Props/CriktBat.act",
    "Act/Props/DDuvet.act",
    "Act/Props/Dish.act",
    "Act/Props/DormTV.act",
    "Act/Props/DunkBench.act",
    "Act/Props/DunkButton.act",
    "Act/Props/FireExt.act",
    "Act/Props/FireHydrant.act",
    "Act/Props/FortTell.act",
    "Act/Props/FrAlrm.act",
    "Act/Props/FruitStand.act",
    "Act/Props/GlueBnch.act",
    "Act/Props/Ladder.act",
    "Act/Props/Looping.act",
    "Act/Props/Mailbox.act",
    "Act/Props/NLockA.act",
    "Act/Props/PoloMalt.act",
    "Act/Props/PrepDoor.act",
    "Act/Props/PunchBag.act",
    "Act/Props/Shield.act",
    "Act/Props/Shower.act",
    "Act/Props/SodaMach.act",
    "Act/Props/StandardDamage.act",
    "Act/Props/StealthDoor.act",
    "Act/Props/Switch.act",
    "Act/Props/Tags.act",
    "Act/Props/TagSmall.act",
    "Act/Props/Toilet.act",
    "Act/Props/Tree.act",
    "Act/Props/TreeFall.act",
    "Act/Props/TrnCarA.act",
    "Act/Props/TrnCarB.act",
    "Act/Props/TrnCarC.act",
    "Act/Props/Urinal.act",
    "Act/Props/WaterFaucet.act",
    "Act/Props/WaterFountain.act",
    "Act/Props/WBrush.act",
    "Act/Props/WPCANNON.act"
}

function F_LoadAllActionTrees() -- ! Modified
    for i, keys in CharacterActionTreesBranches do
        UnLoadBranch(CharacterActionTreesBranches[i])
        --print(CharacterActionTreesBranches[i])
    end
    --[[
    UnLoadBranch("/Global/PlayerTest")
    ]] -- Not present in original script
    for i, keys in CharacterActionTrees do
        Load(CharacterActionTrees[i])
        --print(CharacterActionTrees[i])
    end
    ResolveActionTreeReferences()
end

function F_UnLoadNonDodgeballActionTrees()
    UnLoadBranch("/Global/Actions")
    UnLoadBranch("/Global/Weapons")
    UnLoadBranch("/Global/Vehicles")
    ResolveActionTreeReferences()
end
