local mission_completed = false
local car, ped
local pedmodel = 0
local pedpoint
local pedbacks = 0
local carmodel = MODELENUM._PEUGEOT
local carpoint
local pedchoice = 1
local carchoice = 1
local campoint, tarpoint
local camx, camy, camz = 0, 0, 0
local tarx, tary, tarz = 0, 0, 0
local bCirclePressed = false
local bSquarePressed = false
local bLeftArrowPressed = false
local bRightArrowPressed = false
local bUpArrowPressed = false
local bDownArrowPressed = false
local bTrianglePressed = false
local bTakingPedShots = false
local bTakingCarShots = false
local tblCar = {}
local tblPed = {}
local tblWinterPed = {}
local tblCheerleaders = {}
local tblPrepBW = {}
local tblOldFolks = {}

function F_TableInit()
    pedpoint = POINTLIST._SHOTS_PEDPOINT
    camx, camy, camz = GetPointFromPointList(POINTLIST._SHOTS_TARGET, 1)
    tarx, tary, tarz = GetPointFromPointList(POINTLIST._SHOTS_TARGET, 2)
end

function MissionSetup()
    DATLoad("SHOTS.DAT", 2)
    DATInit()
    Load("Act/Conv/Shots.act")
    F_TableInit()
    HUDClearAllElements()
    AreaTransitionPoint(2, POINTLIST._SHOTS_PLAYERSTART)
    POISetSystemEnabled(false)
    ClockSet(12, 30)
    ClockSetTickRate(0.006)
    WeatherSet(4)
    AreaOverridePopulation(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    AreaClearAllVehicles()
    AreaClearAllPeds()
end

function MissionCleanup()
    DATUnload(2)
    UnLoadBranch("/Global/Shots")
end

function main()
    PedRequestModel(pedmodel)
    ped = PedCreatePoint(0, pedpoint, 1)
    CameraSetXYZ(camx, camy, camz, tarx, tary, tarz)
    while mission_completed == false do
        F_CreateThings()
        Wait(0)
    end
end

function F_Shots_Peds()
    for i = 0, 222 do
        if i < 174 then
            PedRequestModel(i + 1)
        end
        PedDelete(ped)
        ped = PedCreatePoint(i, pedpoint, 1)
        PedStop(ped)
        PedSetActionNode(ped, "/Global/Shots/Shots_Idle", "Act/Conv/Shots.act")
        while not PedIsPlaying(ped, "/Global/Shots/Shots_Idle", false) do
            Wait(0)
        end
        Wait(500)
        DebugScreenShot()
        Wait(250)
        ModelNotNeeded(i)
    end
    CameraReturnToPlayer()
end

function F_Car_Peds()
end

function F_CreateThings()
    if IsButtonPressed(8, 0) and not bCirclePressed and not bTakingPedShots then
        bTakingPedShots = true
        F_Shots_Peds()
    end
    if not IsButtonPressed(6, 0) or bSquarePressed or not bTakingCarShots then
    end
    if IsButtonPressed(9, 0) and not bTrianglePressed then
        PedSetWeapon(ped, 335, 1)
        PedSetActionNode(ped, "/Global/Thrown/ThrownActions/WeaponFire/ThrowFrisbee/ThrowActions/ThrowStart", "Act/Weapons_Thrown.act")
    end
    if not IsButtonPressed(1, 0) or not bLeftArrowPressed then
    end
    if not IsButtonPressed(0, 0) or not bRightArrowPressed then
    end
    if not IsButtonPressed(2, 0) or not bUpArrowPressed then
    end
    if not IsButtonPressed(3, 0) or not bDownArrowPressed then
    end
    if not IsButtonPressed(8, 0) and bCirclePressed then
        bCirclePressed = false
    end
    if not IsButtonPressed(6, 0) and bSquarePressed then
        bSquarePressed = false
    end
    if not IsButtonPressed(0, 0) and bLeftArrowPressed then
        bLeftArrowPressed = false
    end
    if not IsButtonPressed(1, 0) and bRightArrowPressed then
        bRightArrowPressed = false
    end
    if not IsButtonPressed(2, 0) and bUpArrowPressed then
        bUpArrowPressed = false
    end
    if not IsButtonPressed(3, 0) and bDownArrowPressed then
        bDownArrowPressed = false
    end
    if not IsButtonPressed(9, 0) and bTrianglePressed then
        bTrianglePressed = false
    end
end

function F_OldFolks()
    tblOldFolks = {
        {
            index = 100,
            modelid = "TO_NH_Res_01",
            tdx = "TO_NH_Res_01",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 101,
            modelid = "TO_NH_Res_02",
            tdx = "TO_NH_Res_02",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 135,
            modelid = "TO_NH_Res_03",
            tdx = "TO_NH_Res_03",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        }
    }
end

function F_PrepBW()
    tblPrepBW = {
        {
            index = 38,
            modelid = "PRGirl_Pinky_BW",
            tdx = "PRGirl_Pinky_BW",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_GS_FEMALE_A",
            angrp1 = "F_Girls",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 30,
            modelid = "PRH1_Gord_BW",
            tdx = "PRH1_Gord_BW",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_P_STRIKER_B",
            angrp1 = "F_Preps",
            angrp2 = "P_Striker",
            angrp3 = "P_Grappler",
            angrp4 = "Straf_Prep",
            unique = 2,
            actTree = "/Global/P_Striker_B",
            actFile = "Act/Anim/P_Striker_B.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 31,
            modelid = "PRH1a_Tad_BW",
            tdx = "PRH1a_Tad_BW",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_P_STRIKER_A",
            angrp1 = "F_Preps",
            angrp2 = "P_Striker",
            angrp3 = "P_Grappler",
            angrp4 = "Straf_Prep",
            unique = 2,
            actTree = "/Global/P_Striker_A",
            actFile = "Act/Anim/P_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 35,
            modelid = "PRH2_Bryce_BW",
            tdx = "PRH2_Bryce_BW",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_P_GRAPPLER_A ",
            angrp1 = "F_Preps",
            angrp2 = "P_Grappler",
            angrp3 = "null",
            angrp4 = "Straf_Prep",
            unique = 2,
            actTree = "/Global/P_Grappler_A",
            actFile = "Act/Anim/P_Grappler_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 34,
            modelid = "PRH3_Justin_BW",
            tdx = "PRH3_Justin_BW",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_P_STRIKER_B ",
            angrp1 = "F_Preps",
            angrp2 = "P_Striker",
            angrp3 = "P_Grappler",
            angrp4 = "Straf_Prep",
            unique = 2,
            actTree = "/Global/P_Striker_B",
            actFile = "Act/Anim/P_Striker_B.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        }
    }
end

function F_Cheerleaders()
    tblCheerleaders = {
        {
            index = 39,
            modelid = "GN_Asiangirl_CH",
            tdx = "GN_Asiangirl_CH",
            sex = 1,
            size = "Medium",
            fact = "STUDENT",
            stat = "STAT_GS_FEMALE_A",
            angrp1 = "F_Girls",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 67,
            modelid = "GN_Sexygirl_CH",
            tdx = "GN_Sexygirl_CH",
            sex = 1,
            size = "Medium",
            fact = "STUDENT",
            stat = "STAT_GS_FEMALE_S",
            angrp1 = "F_Girls",
            angrp2 = "NPC_Kiss",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 38,
            modelid = "PRGirl_Pinky_CH",
            tdx = "PRGirl_Pinky_CH",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_GS_FEMALE_A",
            angrp1 = "F_Girls",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        }
    }
end

function F_WinterChars()
    tblWinterPed = {
        {
            index = 48,
            modelid = "DOGirl_Zoe_W",
            tdx = "DOGirl_Zoe_W",
            sex = 1,
            size = "Medium",
            fact = "DROPOUT",
            stat = "STAT_GS_FEMALE_A",
            angrp1 = "F_Girls",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 46,
            modelid = "DOH3a_Gurney_W",
            tdx = "DOH3a_Gurney_W",
            sex = 0,
            size = "Large",
            fact = "DROPOUT",
            stat = "STAT_DO_GRAPPLER_A",
            angrp1 = "F_Douts",
            angrp2 = "DO_Grappler",
            angrp3 = "DO_StrikeCombo",
            angrp4 = "Straf_Savage",
            unique = 2,
            actTree = "/Global/DO_Grappler_A",
            actFile = "Act/Anim/DO_Grappler_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 39,
            modelid = "GN_Asiangirl_W",
            tdx = "GN_Asiangirl_W",
            sex = 1,
            size = "Medium",
            fact = "STUDENT",
            stat = "STAT_GS_FEMALE_A",
            angrp1 = "F_Girls",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 102,
            modelid = "GN_Bully01_W",
            tdx = "GN_Bully01_W",
            sex = 0,
            size = "Medium",
            fact = "BULLY",
            stat = "STAT_B_STRIKER_S",
            angrp1 = "Straf_Male",
            angrp2 = "B_Striker",
            angrp3 = "B_Striker_B",
            angrp4 = "GEN_Social",
            unique = 2,
            actTree = "/Global/B_Striker_B",
            actFile = "Act/Anim/B_Striker_B.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 99,
            modelid = "GN_Bully02_W",
            tdx = "GN_Bully02_W",
            sex = 0,
            size = "Medium",
            fact = "BULLY",
            stat = "STAT_B_STRIKER_A",
            angrp1 = "Straf_Male",
            angrp2 = "B_Striker",
            angrp3 = "B_Striker_A",
            angrp4 = "GEN_Social",
            unique = 2,
            actTree = "/Global/B_Striker_A",
            actFile = "Act/Anim/B_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 85,
            modelid = "GN_Bully03_W",
            tdx = "GN_Bully03_W",
            sex = 0,
            size = "Medium",
            fact = "BULLY",
            stat = "STAT_B_STRIKER_B",
            angrp1 = "Straf_Male",
            angrp2 = "B_Striker",
            angrp3 = "B_Striker_B",
            angrp4 = "GEN_Social",
            unique = 2,
            actTree = "/Global/B_Striker_B",
            actFile = "Act/Anim/B_Striker_B.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 146,
            modelid = "GN_Bully05_W",
            tdx = "GN_Bully05_W",
            sex = 0,
            size = "Medium",
            fact = "BULLY",
            stat = "STAT_B_STRIKER_A",
            angrp1 = "Straf_Male",
            angrp2 = "B_Striker",
            angrp3 = "B_Striker_A",
            angrp4 = "GEN_Social",
            unique = 2,
            actTree = "/Global/B_Striker_A",
            actFile = "Act/Anim/B_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 71,
            modelid = "GN_Fatboy_W",
            tdx = "GN_Fatboy_W",
            sex = 1,
            size = "Medium",
            fact = "STUDENT",
            stat = "STAT_GS_MALE_A",
            angrp1 = "Straf_Fat",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "null",
            unique = 2,
            actTree = "/Global/GS_Fat_A",
            actFile = "Act/Anim/GS_Fat_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 74,
            modelid = "GN_Fatgirl_W",
            tdx = "GN_Fatgirl_W",
            sex = 0,
            size = "Medium",
            fact = "STUDENT",
            stat = "STAT_GS_FEMALE_A",
            angrp1 = "F_Girls",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Fat_A",
            actFile = "Act/Anim/GS_Fat_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 66,
            modelid = "GN_Littleblkboy_W",
            tdx = "GN_Littleblkboy_W",
            sex = 0,
            size = "Small",
            fact = "STUDENT",
            stat = "STAT_GS_MALE_A",
            angrp1 = "null",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/GS_Male_A",
            actFile = "Act/Anim/GS_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 68,
            modelid = "GN_Littleblkgirl_W",
            tdx = "GN_Littleblkgirl_W",
            sex = 1,
            size = "Small",
            fact = "STUDENT",
            stat = "STAT_GS_FEMALE_A",
            angrp1 = "F_Girls",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 137,
            modelid = "GN_LittleGirl_2_W",
            tdx = "GN_LittleGirl_2_W",
            sex = 1,
            size = "Small",
            fact = "STUDENT",
            stat = "STAT_GS_FEMALE_A",
            angrp1 = "F_Girls",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 138,
            modelid = "GN_LittleGirl_3_W",
            tdx = "GN_LittleGirl_3_W",
            sex = 1,
            size = "Small",
            fact = "STUDENT",
            stat = "STAT_GS_FEMALE_A",
            angrp1 = "F_Girls",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 67,
            modelid = "GN_Sexygirl_W",
            tdx = "GN_Sexygirl_W",
            sex = 1,
            size = "Medium",
            fact = "STUDENT",
            stat = "STAT_GS_FEMALE_S",
            angrp1 = "F_Girls",
            angrp2 = "NPC_Kiss",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 71,
            modelid = "GN_WhiteBoy_W",
            tdx = "GN_WhiteBoy_W",
            sex = 0,
            size = "Medium",
            fact = "STUDENT",
            stat = "STAT_GS_MALE_A",
            angrp1 = "Straf_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "null",
            unique = 2,
            actTree = "/Global/GS_Male_A",
            actFile = "Act/Anim/GS_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 21,
            modelid = "GR2nd_Peanut_W",
            tdx = "GR2nd_Peanut_W",
            sex = 0,
            size = "Medium",
            fact = "GREASER",
            stat = "STAT_G_STRIKER_A",
            angrp1 = "F_Greas",
            angrp2 = "G_Strike",
            angrp3 = "null",
            angrp4 = "null",
            unique = 2,
            actTree = "/Global/G_Striker_A",
            actFile = "Act/Anim/G_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 26,
            modelid = "GRH3_Lucky_W",
            tdx = "GRH3_Lucky_W",
            sex = 0,
            size = "Medium",
            fact = "GREASER",
            stat = "STAT_G_RANGED_A",
            angrp1 = "F_Greas",
            angrp2 = "G_Strike",
            angrp3 = "G_Ranged",
            angrp4 = "null",
            unique = 2,
            actTree = "/Global/G_Ranged_A",
            actFile = "Act/Anim/G_Ranged_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 28,
            modelid = "GRH3a_Ricky_W",
            tdx = "GRH3a_Ricky_W",
            sex = 0,
            size = "Medium",
            fact = "GREASER",
            stat = "STAT_G_RANGED_A",
            angrp1 = "F_Greas",
            angrp2 = "G_Strike",
            angrp3 = "null",
            angrp4 = "null",
            unique = 2,
            actTree = "/Global/G_Ranged_A",
            actFile = "Act/Anim/G_Ranged_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 23,
            modelid = "GRlead_Johnny_W",
            tdx = "GRlead_Johnny_W",
            sex = 0,
            size = "Medium",
            fact = "GREASER",
            stat = "STAT_G_JOHNNY",
            angrp1 = "F_Greas",
            angrp2 = "G_Johnny",
            angrp3 = "null",
            angrp4 = "null",
            unique = 2,
            actTree = "/Global/G_Johnny",
            actFile = "Act/Anim/G_Johnny.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 14,
            modelid = "JKGirl_Mandy_W",
            tdx = "JKGirl_Mandy_W",
            sex = 1,
            size = "Medium",
            fact = "JOCK",
            stat = "STAT_GS_FEMALE_A",
            angrp1 = "F_Girls",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 12,
            modelid = "JKH1_Damon_W",
            tdx = "JKH1_Damon_W",
            sex = 0,
            size = "Large",
            fact = "JOCK",
            stat = "STAT_J_DAMON",
            angrp1 = "F_Jocks",
            angrp2 = "J_Striker",
            angrp3 = "J_Damon",
            angrp4 = "J_Grappler",
            unique = 2,
            actTree = "/Global/J_Striker_A",
            actFile = "Act/Anim/J_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 13,
            modelid = "JKH1a_KirbyWinter",
            tdx = "JKH1a_KirbyWinter",
            sex = 0,
            size = "Medium",
            fact = "JOCK",
            stat = "STAT_J_STRIKER_A",
            angrp1 = "F_Jocks",
            angrp2 = "J_Striker",
            angrp3 = "null",
            angrp4 = "null",
            unique = 2,
            actTree = "/Global/J_Striker_A",
            actFile = "Act/Anim/J_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 15,
            modelid = "JKH2_DanWinter",
            tdx = "JKH2_DanWinter",
            sex = 0,
            size = "Medium",
            fact = "JOCK",
            stat = "STAT_J_STRIKER_A",
            angrp1 = "F_Jocks",
            angrp2 = "J_Striker",
            angrp3 = "null",
            angrp4 = "null",
            unique = 2,
            actTree = "/Global/J_Striker_A",
            actFile = "Act/Anim/J_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 19,
            modelid = "JKlead_Ted_W",
            tdx = "JKlead_Ted_W",
            sex = 0,
            size = "Medium",
            fact = "JOCK",
            stat = "STAT_J_TED",
            angrp1 = "F_Jocks",
            angrp2 = "J_Striker",
            angrp3 = "null",
            angrp4 = "null",
            unique = 2,
            actTree = "/Global/J_Striker_A",
            actFile = "Act/Anim/J_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 6,
            modelid = "ND2nd_Melvin_W",
            tdx = "ND2nd_Melvin_W",
            sex = 0,
            size = "Medium",
            fact = "NERD",
            stat = "STAT_N_STRIKER_A",
            angrp1 = "F_Nerds",
            angrp2 = "N_Striker",
            angrp3 = "N_Striker_A",
            angrp4 = "Straf_Fat",
            unique = 2,
            actTree = "/Global/N_Striker_A",
            actFile = "Act/Anim/N_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 3,
            modelid = "NDGirl_Beatrice_W",
            tdx = "NDGirl_Beatrice_W",
            sex = 1,
            size = "Medium",
            fact = "NERD",
            stat = "STAT_GS_FEMALE_A",
            angrp1 = "F_Girls",
            angrp2 = "Straf_Female",
            angrp3 = "null",
            angrp4 = "null",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 5,
            modelid = "NDH1_Fatty_W",
            tdx = "NDH1_Fatty_W",
            sex = 0,
            size = "Medium",
            fact = "NERD",
            stat = "STAT_N_STRIKER_A",
            angrp1 = "F_Nerds",
            angrp2 = "N_Striker",
            angrp3 = "N_Striker_A",
            angrp4 = "Straf_Fat",
            unique = 2,
            actTree = "/Global/N_Striker_A",
            actFile = "Act/Anim/N_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 4,
            modelid = "NDH1a_Algernon_W",
            tdx = "NDH1a_Algernon_W",
            sex = 0,
            size = "Medium",
            fact = "NERD",
            stat = "STAT_N_STRIKER_B",
            angrp1 = "F_Nerds",
            angrp2 = "N_Striker",
            angrp3 = "N_Striker_B",
            angrp4 = "Straf_Fat",
            unique = 2,
            actTree = "/Global/N_Striker_B",
            actFile = "Act/Anim/N_Striker_B.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 7,
            modelid = "NDH2_Thad_W",
            tdx = "NDH2_Thad_W",
            sex = 0,
            size = "Medium",
            fact = "NERD",
            stat = "STAT_N_MELEE_A",
            angrp1 = "F_Nerds",
            angrp2 = "N_Melee",
            angrp3 = "null",
            angrp4 = "Straf_Nerd",
            unique = 2,
            actTree = "/Global/N_Melee_A",
            actFile = "Act/Anim/N_Melee_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 9,
            modelid = "NDH2a_Cornelius_W",
            tdx = "NDH2a_Cornelius_W",
            sex = 0,
            size = "Medium",
            fact = "NERD",
            stat = "STAT_N_MELEE_A",
            angrp1 = "F_Nerds",
            angrp2 = "N_Melee",
            angrp3 = "null",
            angrp4 = "Straf_Nerd",
            unique = 2,
            actTree = "/Global/N_Melee_A",
            actFile = "Act/Anim/N_Melee_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 8,
            modelid = "NDH3_Bucky_W",
            tdx = "NDH3_Bucky_W",
            sex = 0,
            size = "Medium",
            fact = "NERD",
            stat = "STAT_N_RANGED_S",
            angrp1 = "F_Nerds",
            angrp2 = "N_Strike",
            angrp3 = "N_Ranged",
            angrp4 = "Straf_Nerd",
            unique = 2,
            actTree = "/Global/N_Ranged_A",
            actFile = "Act/Anim/N_Ranged_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 11,
            modelid = "NDH3a_Donald_W",
            tdx = "NDH3a_Donald_W",
            sex = 0,
            size = "Medium",
            fact = "NERD",
            stat = "STAT_N_RANGED_A",
            angrp1 = "F_Nerds",
            angrp2 = "N_Strike",
            angrp3 = "N_Ranged",
            angrp4 = "Straf_Nerd",
            unique = 2,
            actTree = "/Global/N_Ranged_A",
            actFile = "Act/Anim/N_Ranged_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 10,
            modelid = "NDlead_Earnest_W",
            tdx = "NDlead_Earnest_W",
            sex = 0,
            size = "Medium",
            fact = "NERD",
            stat = "STAT_N_EARNEST",
            angrp1 = "F_Nerds",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Nerd",
            unique = 2,
            actTree = "/Global/N_Melee_A",
            actFile = "Act/Anim/N_Melee_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 130,
            modelid = "Nemesis_Gary_W",
            tdx = "Nemesis_Gary_W",
            sex = 0,
            size = "Medium",
            fact = "STUDENT",
            stat = "STAT_GS_MALE_A",
            angrp1 = "Straf_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "null",
            unique = -1,
            actTree = "/Global/GS_Male_A",
            actFile = "Act/Anim/GS_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 134,
            modelid = "Peter_W",
            tdx = "Peter_W",
            sex = 0,
            size = "Medium",
            fact = "STUDENT",
            stat = "STAT_GS_MALE_A",
            angrp1 = "Straf_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "null",
            unique = -1,
            actTree = "/Global/GS_Male_A",
            actFile = "Act/Anim/GS_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 49,
            modelid = "PF2nd_Max_W",
            tdx = "PF2nd_Max_W",
            sex = 0,
            size = "Large",
            fact = "PREFECT",
            stat = "STAT_PF_BASIC_A",
            angrp1 = "F_Pref",
            angrp2 = "PF_Basic",
            angrp3 = "null",
            angrp4 = "null",
            unique = -1,
            actTree = "/Global/PF_Basic_A",
            actFile = "Act/Anim/PF_Basic_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 38,
            modelid = "PRGirl_Pinky_W",
            tdx = "PRGirl_Pinky_W",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_GS_FEMALE_A",
            angrp1 = "F_Girls",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/GS_Female_A",
            actFile = "Act/Anim/GS_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 30,
            modelid = "PRH1_Gord_W",
            tdx = "PRH1_Gord_W",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_P_STRIKER_B",
            angrp1 = "F_Preps",
            angrp2 = "P_Striker",
            angrp3 = "P_Grappler",
            angrp4 = "Straf_Prep",
            unique = 2,
            actTree = "/Global/P_Striker_B",
            actFile = "Act/Anim/P_Striker_B.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 31,
            modelid = "PRH1a_Tad_W",
            tdx = "PRH1a_Tad_W",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_P_STRIKER_A",
            angrp1 = "F_Preps",
            angrp2 = "P_Striker",
            angrp3 = "P_Grappler",
            angrp4 = "Straf_Prep",
            unique = 2,
            actTree = "/Global/P_Striker_A",
            actFile = "Act/Anim/P_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 35,
            modelid = "PRH2_Bryce_W",
            tdx = "PRH2_Bryce_W",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_P_GRAPPLER_A ",
            angrp1 = "F_Preps",
            angrp2 = "P_Grappler",
            angrp3 = "null",
            angrp4 = "Straf_Prep",
            unique = 2,
            actTree = "/Global/P_Grappler_A",
            actFile = "Act/Anim/P_Grappler_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 32,
            modelid = "PRH2_Chad_W",
            tdx = "PRH2_Chad_W",
            sex = 0,
            size = "Large",
            fact = "PREPPY",
            stat = "STAT_P_STRIKER_A ",
            angrp1 = "F_Preps",
            angrp2 = "P_Striker",
            angrp3 = "P_Grappler",
            angrp4 = "Straf_Prep",
            unique = 2,
            actTree = "/Global/P_Striker_A",
            actFile = "Act/Anim/P_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 34,
            modelid = "PRH3_Justin_W",
            tdx = "PRH3_Justin_W",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_P_STRIKER_B ",
            angrp1 = "F_Preps",
            angrp2 = "P_Striker",
            angrp3 = "P_Grappler",
            angrp4 = "Straf_Prep",
            unique = 2,
            actTree = "/Global/P_Striker_B",
            actFile = "Act/Anim/P_Striker_B.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 40,
            modelid = "PRH3a_Parker_W",
            tdx = "PRH3a_Parker_W",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_P_STRIKER_B ",
            angrp1 = "F_Preps",
            angrp2 = "P_Striker",
            angrp3 = "null",
            angrp4 = "Straf_Prep",
            unique = 2,
            actTree = "/Global/P_Striker_B",
            actFile = "Act/Anim/P_Striker_B.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 37,
            modelid = "PRlead_Darby_W",
            tdx = "PRlead_Darby_W",
            sex = 0,
            size = "Medium",
            fact = "PREPPY",
            stat = "STAT_P_BOXING ",
            angrp1 = "F_Preps",
            angrp2 = "P_Striker",
            angrp3 = "null",
            angrp4 = "Straf_Prep",
            unique = -1,
            actTree = "/Global/P_Striker_A",
            actFile = "Act/Anim/P_Striker_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 126,
            modelid = "TE_Autoshop_W",
            tdx = "TE_Autoshop_W",
            sex = 0,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_MALE_A ",
            angrp1 = "TE_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/TE_Male_A",
            actFile = "Act/Anim/TE_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 64,
            modelid = "TE_Biology_W",
            tdx = "TE_Biology_W",
            sex = 0,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_MALE_A ",
            angrp1 = "TE_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/TE_Male_A",
            actFile = "Act/Anim/TE_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 106,
            modelid = "TE_Chemistry_W",
            tdx = "TE_Chemistry_W",
            sex = 0,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_MALE_A ",
            angrp1 = "TE_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/TE_Male_A",
            actFile = "Act/Anim/TE_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 57,
            modelid = "TE_Chemistry_W",
            tdx = "TE_Chemistry_W",
            sex = 0,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_MALE_A ",
            angrp1 = "TE_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/TE_Male_A",
            actFile = "Act/Anim/TE_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 55,
            modelid = "TE_GymTeacher_W",
            tdx = "TE_GymTeacher_W",
            sex = 0,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_MALE_A ",
            angrp1 = "TE_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/TE_Male_A",
            actFile = "Act/Anim/TE_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 54,
            modelid = "TE_Hallmonitor_W",
            tdx = "TE_Hallmonitor_W",
            sex = 1,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_FEMALE_A ",
            angrp1 = "TE_Female",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/TE_Female_A",
            actFile = "Act/Anim/TE_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 62,
            modelid = "TE_Librarian_W",
            tdx = "TE_Librarian_W",
            sex = 1,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_FEMALE_A ",
            angrp1 = "TE_Female",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/TE_Female_A",
            actFile = "Act/Anim/TE_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 61,
            modelid = "TE_MathTeacher_W",
            tdx = "TE_MathTeacher_W",
            sex = 0,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_MALE_A ",
            angrp1 = "TE_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/TE_Male_A",
            actFile = "Act/Anim/TE_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 60,
            modelid = "TE_Nurse_W",
            tdx = "TE_Nurse_W",
            sex = 1,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_FEMALE_A ",
            angrp1 = "TE_Female",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/TE_Female_A",
            actFile = "Act/Anim/TE_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 65,
            modelid = "TE_Principal_W",
            tdx = "TE_Principal_W",
            sex = 0,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_MALE_A ",
            angrp1 = "TE_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/TE_Male_A",
            actFile = "Act/Anim/TE_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 148,
            modelid = "TO_Business4_W",
            tdx = "TO_Business4_W",
            sex = 0,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_MALE_A ",
            angrp1 = "TE_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/TE_Male_A",
            actFile = "Act/Anim/TE_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 149,
            modelid = "TO_Business5_W",
            tdx = "TO_Business5_W",
            sex = 0,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_MALE_A ",
            angrp1 = "TE_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/TE_Male_A",
            actFile = "Act/Anim/TE_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 76,
            modelid = "TO_BusinessW1_W",
            tdx = "TO_BusinessW1_W",
            sex = 0,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_MALE_A ",
            angrp1 = "TE_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/TE_Male_A",
            actFile = "Act/Anim/TE_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 144,
            modelid = "TO_BusinessW2_W",
            tdx = "TO_BusinessW2_W",
            sex = 0,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_MALE_A ",
            angrp1 = "TE_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/TE_Male_A",
            actFile = "Act/Anim/TE_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 78,
            modelid = "TO_BusinessW1_W",
            tdx = "TO_BusinessW1_W",
            sex = 1,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_FEMALE_A ",
            angrp1 = "TE_Female",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/TE_Female_A",
            actFile = "Act/Anim/TE_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 79,
            modelid = "TO_BusinessW2_W",
            tdx = "TO_BusinessW2_W",
            sex = 1,
            size = "Large",
            fact = "TEACHER",
            stat = "STAT_TE_FEMALE_A ",
            angrp1 = "TE_Female",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/TE_Female_A",
            actFile = "Act/Anim/TE_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 140,
            modelid = "TO_Carnie_fem_W",
            tdx = "TO_Carnie_fem_W",
            sex = 1,
            size = "Medium",
            fact = "TOWNPERSON",
            stat = "STAT_CV_FEMALE_A ",
            angrp1 = "CV_Female",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/CV_Female_A",
            actFile = "Act/Anim/CV_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 155,
            modelid = "TO_CarnyMidget_W",
            tdx = "TO_CarnyMidget_W",
            sex = 0,
            size = "Small",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 157,
            modelid = "TO_Handy_W",
            tdx = "TO_Handy_W",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 87,
            modelid = "TO_Hobo_W",
            tdx = "TO_Hobo_W",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 123,
            modelid = "TO_Industrial_W",
            tdx = "TO_Industrial_W",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 127,
            modelid = "TO_Mailman_W",
            tdx = "TO_Mailman_W",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 148,
            modelid = "TO_Millworker",
            tdx = "TO_Millworker",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 108,
            modelid = "TO_Motelowner_W",
            tdx = "TO_Motelowner_W",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 148,
            modelid = "TO_Orderly_W",
            tdx = "TO_Orderly_W",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 116,
            modelid = "TO_Poorman2_W",
            tdx = "TO_Poorman2_W",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 107,
            modelid = "TO_Poorwoman_W",
            tdx = "TO_Poorwoman_W",
            sex = 1,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_FEMALE_A ",
            angrp1 = "TE_Female",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/CV_Female_A",
            actFile = "Act/Anim/CV_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 100,
            modelid = "TO_RichM1_W",
            tdx = "TO_RichM1_W",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 101,
            modelid = "TO_RichM2_W",
            tdx = "TO_RichM2_W",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 135,
            modelid = "TO_RichM3_W",
            tdx = "TO_RichM3_W",
            sex = 0,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_MALE_A ",
            angrp1 = "CV_Male",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Male",
            unique = 2,
            actTree = "/Global/CV_Male_A",
            actFile = "Act/Anim/CV_Male_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        },
        {
            index = 80,
            modelid = "TO_RichW1_W",
            tdx = "TO_RichW1_W",
            sex = 1,
            size = "Large",
            fact = "TOWNPERSON",
            stat = "STAT_CV_FEMALE_A ",
            angrp1 = "TE_Female",
            angrp2 = "null",
            angrp3 = "null",
            angrp4 = "Straf_Female",
            unique = 2,
            actTree = "/Global/CV_Female_A",
            actFile = "Act/Anim/CV_Female_A.act",
            aiTree = "/Global/AI",
            aiFile = "Act/AI/AI.act"
        }
    }
end

function F_MakeBabies(tbl)
    for i, entry in tbl do
        SetupPedObject(entry.index, entry.modelid, entry.tdx, entry.sex, entry.size, entry.fact, entry.stat, entry.angrp1, entry.angrp2, entry.angrp3, entry.angrp4, entry.unique, entry.actTree, entry.actFile, entry.aiTree, entry.aiFile)
    end
end
